// Source basis: curated from publicly listed Nigerian commercial/non-interest banks.
// Last reviewed: 2026-08-07.
export const NIGERIAN_BANKS = [
    "Access Bank",
    "Citibank Nigeria",
    "Ecobank Nigeria",
    "Fidelity Bank",
    "First Bank of Nigeria",
    "First City Monument Bank (FCMB)",
    "Globus Bank",
    "Guaranty Trust Bank (GTBank)",
    "Jaiz Bank",
    "Keystone Bank",
    "Lotus Bank",
    "Nova Commercial Bank",
    "Optimus Bank",
    "Parallex Bank",
    "Polaris Bank",
    "PremiumTrust Bank",
    "Providus Bank",
    "Signature Bank",
    "Stanbic IBTC Bank",
    "Standard Chartered Bank Nigeria",
    "Sterling Bank",
    "SunTrust Bank Nigeria",
    "TAJBank",
    "The Alternative Bank",
    "Titan Trust Bank",
    "Union Bank of Nigeria",
    "United Bank for Africa (UBA)",
    "Unity Bank",
    "Wema Bank",
    "Zenith Bank",
    "Kuda Microfinance Bank",
    "Moniepoint Microfinance Bank",
    "OPay",
    "PalmPay",
    "VFD Microfinance Bank",
    "FairMoney Microfinance Bank",
    "Sparkle Microfinance Bank",
    "Dot Microfinance Bank",
    "Rubies Microfinance Bank",
    "Mkobo Microfinance Bank",
    "Rex Microfinance Bank",
] as const
